name: Seeed reTerminal Yocto embedded linux

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai


# Action will return to the startup working directory every run
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Check disk usage before build
        run: df -h
        
      - name: Setup yocto
        run: |
            cd ${{ github.workspace }}
            git clone -b master git://git.yoctoproject.org/poky
            cd poky/
            git reset --hard 7ade8346b3a09983257589d22aaada47e0eec010
            df -h

      - name: Building targets
        run: |
            cd ${{ github.workspace }}/poky
            git clone -b main https://github.com/Seeed-Studio/meta-seeed-reterminal.git
            cp meta-seeed-reterminal/build-*.sh ./
            chmod +x build-*.sh
            ./build-raspberrypi4-64-image.sh

      - name: Check disk usage after build
        run: df -h

      - name: Pack
        run: |
            cd ${{ github.workspace }}/poky/build/tmp
            tar -Jcf yocto-image.tar.xz deploy/images
            echo "PACKAGE=${{ github.workspace }}/poky/build/tmp/yocto-image.tar.xz" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: yocto deploy
          path: ${{env.PACKAGE}}

